### ISSUE TITLE
Include shellCheck in travis builds 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/test-tools#95]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

- Multiple images in the test-tools repo make use of bash scripts as the container business logic. They need to be validated via shellCheck utility as part of sanity checks before building/pushing the images. 

Ref: https://dev.to/david_j_eddy/using-shellcheck-to-lint-your-bashsh-scripts-3jaf

**Comment by biswaroop1547** [comment]
I am doing this
